#include "storage.h"

#include <fstream>
#include <sstream>
#include <iostream>

using namespace std;

// --------------------------------------------------
// LOAD TASKS FROM FILE
// --------------------------------------------------

vector<Task> loadTasks(const string& filename)
{
    vector<Task> tasks;

    ifstream file(filename);

    if(!file)
    {
        cout << "Failed to open tasks file.\n";
        return tasks;
    }

    string line;

    while(getline(file, line))
    {
        stringstream ss(line);

        Task task;

        string priorityStr;

        getline(ss, task.subject, '|');

        getline(ss, task.topic, '|');

        getline(ss, task.deadline, '|');

        getline(ss, priorityStr, '|');

        getline(ss, task.status, '|');

        task.priority = stoi(priorityStr);

        tasks.push_back(task);
    }

    file.close();

    return tasks;
}

// --------------------------------------------------
// SAVE TASKS TO FILE
// --------------------------------------------------

void saveTasks(
    const vector<Task>& tasks,
    const string& filename
)
{
    ofstream file(filename);

    if(!file)
    {
        cout << "Failed to save tasks.\n";
        return;
    }

    for(const auto& task : tasks)
    {
        file
        << task.subject << "|"
        << task.topic << "|"
        << task.deadline << "|"
        << task.priority << "|"
        << task.status << "\n";
    }

    file.close();

    cout << "Tasks saved successfully.\n";
}

// --------------------------------------------------
// EXPORT PLAN
// --------------------------------------------------

void exportPlan(const vector<Task>& tasks)
{
    ofstream file("study_plan_export.txt");

    if(!file)
    {
        cout << "Export failed.\n";
        return;
    }

    file
    << "========================================\n";

    file
    << "         AI STUDY PLANNER REPORT\n";

    file
    << "========================================\n\n";

    int completed = 0;
    int pending = 0;

    for(const auto& task : tasks)
    {
        if(task.status == "DONE")
            completed++;
        else
            pending++;
    }

    int productivity =
    (completed * 100) / tasks.size();

    // ------------------------------------
    // Summary
    // ------------------------------------

    file
    << "SUMMARY\n";

    file
    << "----------------------------------------\n";

    file
    << "Total Tasks      : "
    << tasks.size() << "\n";

    file
    << "Completed Tasks  : "
    << completed << "\n";

    file
    << "Pending Tasks    : "
    << pending << "\n";

    file
    << "Productivity     : "
    << productivity << "%\n\n";

    // ------------------------------------
    // Tasks
    // ------------------------------------

    file
    << "TASK DETAILS\n";

    file
    << "----------------------------------------\n\n";

    int count = 1;

    for(const auto& task : tasks)
    {
        file
        << "Task #" << count++ << "\n\n";

        file
        << "Subject    : "
        << task.subject << "\n";

        file
        << "Topic      : "
        << task.topic << "\n";

        file
        << "Deadline   : "
        << task.deadline << "\n";

        file
        << "Priority   : ";

        if(task.priority == 1)
            file << "HIGH";
        else if(task.priority == 2)
            file << "MEDIUM";
        else
            file << "LOW";

        file << "\n";

        file
        << "Status     : "
        << task.status << "\n";

        // --------------------------------
        // AI Remark
        // --------------------------------

        file
        << "AI Remark  : ";

        if(task.status == "DONE")
        {
            file
            << "Excellent progress.\n";
        }
        else if(task.priority == 1)
        {
            file
            << "Requires immediate attention.\n";
        }
        else
        {
            file
            << "Can be scheduled flexibly.\n";
        }

        file
        << "\n----------------------------------------\n\n";
    }

    // ------------------------------------
    // Footer
    // ------------------------------------

    file
    << "Generated By : AI STUDY PLANNER AGENT\n";

    file
    << "Engine       : Gemini AI + Min Heap\n";

    file
    << "========================================\n";

    file.close();
}
    